new feature remove sampel bulk
jabardigitalservice/pikobar-labkes-satelit pull request #135
Opened 2021-02-02 09:45 UTC by ayocodingit

[OVERVIEW]

new feature remove sampel bulk

cc: @aldidoanta @rindibudiaramdhan @jabardigitalservice/jds-backend

2021-02-02 12:04 UTC, rindibudiaramdhan requested changes

2021-02-02 12:04 UTC, rindibudiaramdhan commented on backend/app/Http/Controllers/V1/DeleteSampelBulkController.php
> +        }
ini kalau versi raw query langsung di SQL Editornya bisa ga kang? @ayocodingit 
harapannya bisa lebih simple codenya

2021-02-02 12:05 UTC, ayocodingit commented on backend/app/Http/Controllers/V1/DeleteSampelBulkController.php
> +        }
Query gimna kang ?

2021-02-03 03:10 UTC, aldidoanta commented on backend/app/Http/Controllers/V1/DeleteSampelBulkController.php
> +        }
mungkin maksudnya pakai Raw Expression ya kang @rindibudiaramdhan?

https://laravel.com/docs/8.x/queries#raw-expressions

btw kang @ayocodingit , untuk `foreeach` di atas, nggak masalah ya kalau variabel `$register` dipakai seperti itu?

```
foreach ($register as $register) {
```

2021-02-03 03:41 UTC, rindibudiaramdhan commented on backend/app/Http/Controllers/V1/DeleteSampelBulkController.php
> +        }
harapan saya sih sebenarnya ingin menggantikan proses `foreach` dan `if` ini sih kang @aldidoanta @ayocodingit

2021-02-03 03:57 UTC, ayocodingit commented on backend/app/Http/Controllers/V1/DeleteSampelBulkController.php
> +        }
`foreach ($register as $register) {`

aman kang

2021-02-03 04:42 UTC, aldidoanta commented on backend/app/Http/Controllers/V1/DeleteSampelBulkController.php
> +        }
kang @ayocodingit , mau tanya dulu. `Register` kan punya relation `hasOne` ke `Sampel`. Waktu bikin foreign key, udah pakai cascade delete blm kang? Misalnya:

```php
$table
    ->foreign('venue_id')
    ->references('id')
    ->on('venues')
    ->onDelete('cascade');
```

Kalau udah pakai cascade delete, harusnya waktu `Register` di-delete, `Sampel` juga akan langsung di-delete. Jadi harusnya code yang ini sudah tidak perlu

```php
if ($register->sampel) {
    $register->sampel()->delete();
}
```

2021-02-03 04:44 UTC, ayocodingit commented on backend/app/Http/Controllers/V1/DeleteSampelBulkController.php
> +        }
kalau pakai `onDelete` itu bukannya hard delete bukan kang ?

2021-02-03 08:22 UTC, ayocodingit commented on backend/app/Http/Controllers/V1/DeleteSampelBulkController.php
> +        }
ini sudah di refactor kang @rindibudiaramdhan 

cc: @aldidoanta

2021-02-03 09:17 UTC, rindibudiaramdhan approved these changes

2021-02-03 09:17 UTC, rindibudiaramdhan commented
sip gaes!

2021-02-03 10:55 UTC, aldidoanta approved these changes

2021-02-03 10:57 UTC, aldidoanta commented on backend/app/Http/Controllers/V1/DeleteSampelBulkController.php
> +        }
Sip mantap kang :+1: 
Oh soalnya model `Register` pakai soft delete ya, sipsip

2021-02-03 10:58 UTC, merged